/**
 * Copyright (c) 2009 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contribution:
 * 		Florian Pirchner - Changed code for Lunifera
 */
package org.lunifera.ide.core.ui.project;

import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IProject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.ui.util.IProjectFactoryContributor;
import org.lunifera.ide.core.ui.project.DefaultProjectFactoryContributor;
import org.lunifera.ide.core.ui.project.FileUtil;
import org.lunifera.ide.core.ui.project.LuniferaProjectInfo;

/**
 * Contributes build.properties file and the launch configuration file to a new dsl test project
 * @author Dennis Huebner - Initial contribution and API
 * @since 2.3
 */
@SuppressWarnings("all")
public class AggregatorProjectContributor extends DefaultProjectFactoryContributor {
  private LuniferaProjectInfo projectInfo;
  
  public AggregatorProjectContributor(final LuniferaProjectInfo projectInfo) {
    this.projectInfo = projectInfo;
  }
  
  public void contributeFiles(final IProject project, final IProjectFactoryContributor.IFileCreator fileWriter) {
    String _targetPlatformFile = this.targetPlatformFile();
    fileWriter.writeToFile(_targetPlatformFile, "/setup/targetplatform.target");
    this.contributeMarker(fileWriter);
    this.contributeBuildProperties(fileWriter);
    this.contributeLaunchConfig(fileWriter);
    this.contributePom(fileWriter);
  }
  
  private String targetPlatformFile() {
    return FileUtil.readFile("data/targetplatform.target-template");
  }
  
  private IFile contributeMarker(final IProjectFactoryContributor.IFileCreator fileWriter) {
    StringConcatenation _builder = new StringConcatenation();
    return this.writeToFile(_builder, fileWriter, ".lunifera.releng.root");
  }
  
  private IFile contributeBuildProperties(final IProjectFactoryContributor.IFileCreator fileWriter) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("source.. = src/,\\");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("src-gen/,\\");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("xtend-gen/");
    _builder.newLine();
    _builder.append("bin.includes = META-INF/,\\");
    _builder.newLine();
    _builder.append("       ");
    _builder.append(".");
    _builder.newLine();
    return this.writeToFile(_builder, fileWriter, "build.properties");
  }
  
  private IFile contributeTargetDefinition(final IProjectFactoryContributor.IFileCreator fileWriter) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>");
    _builder.newLine();
    _builder.append("<?pde version=\"3.8\"?>");
    _builder.newLine();
    _builder.append("<target name=\"Carstore Targetdefinition\" sequenceNumber=\"14\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<locations>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<location includeAllPlatforms=\"false\" includeConfigurePhase=\"true\" includeMode=\"slicer\" includeSource=\"true\" type=\"InstallableUnit\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<unit id=\"org.lunifera.runtime.feature.allinone.feature.group\" version=\"0.8.1.201501301423\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<unit id=\"org.lunifera.runtime.feature.allinone.source.feature.group\" version=\"0.8.1.201501301423\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<repository location=\"http://lun.lunifera.org/downloads/p2/lunifera/luna/latest/\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</location>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</locations>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<environment>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<arch>x86_64</arch>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<nl>de_AT</nl>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</environment>");
    _builder.newLine();
    _builder.append("</target>");
    _builder.newLine();
    return this.writeToFile(_builder, fileWriter, "setup/targetplatform.target");
  }
  
  private IFile contributeLaunchConfig(final IProjectFactoryContributor.IFileCreator fileWriter) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>");
    _builder.newLine();
    _builder.append("<launchConfiguration type=\"org.eclipse.jdt.junit.launchconfig\">");
    _builder.newLine();
    _builder.append("<listAttribute key=\"org.eclipse.debug.core.MAPPED_RESOURCE_PATHS\">");
    _builder.newLine();
    _builder.append("<listEntry value=\"/�projectInfo.testProjectName�\"/>");
    _builder.newLine();
    _builder.append("</listAttribute>");
    _builder.newLine();
    _builder.append("<listAttribute key=\"org.eclipse.debug.core.MAPPED_RESOURCE_TYPES\">");
    _builder.newLine();
    _builder.append("<listEntry value=\"4\"/>");
    _builder.newLine();
    _builder.append("</listAttribute>");
    _builder.newLine();
    _builder.append("<stringAttribute key=\"org.eclipse.jdt.junit.CONTAINER\" value=\"=�projectInfo.testProjectName�\"/>");
    _builder.newLine();
    _builder.append("<booleanAttribute key=\"org.eclipse.jdt.junit.KEEPRUNNING_ATTR\" value=\"false\"/>");
    _builder.newLine();
    _builder.append("<stringAttribute key=\"org.eclipse.jdt.junit.TEST_KIND\" value=\"org.eclipse.jdt.junit.loader.junit4\"/>");
    _builder.newLine();
    _builder.append("<stringAttribute key=\"org.eclipse.jdt.launching.PROJECT_ATTR\" value=\"�projectInfo.testProjectName�\"/>");
    _builder.newLine();
    _builder.append("</launchConfiguration>");
    _builder.newLine();
    String _testProjectName = this.projectInfo.getTestProjectName();
    String _plus = (_testProjectName + ".launch");
    return this.writeToFile(_builder, fileWriter, _plus);
  }
  
  private IFile contributePom(final IProjectFactoryContributor.IFileCreator fileWriter) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\t");
    _builder.append("<project xmlns=\"http://maven.apache.org/POM/4.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<modelVersion>4.0.0</modelVersion>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<parent>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<groupId>org.lunifera.releng.maven</groupId>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<artifactId>lunifera-releng-maven-parent-tycho</artifactId>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<version>0.12.3-SNAPSHOT</version>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</parent>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<groupId>");
    String _projectName = this.projectInfo.getProjectName();
    _builder.append(_projectName, "\t");
    _builder.append("</groupId>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<artifactId>");
    String _aggregatorProjectName = this.projectInfo.getAggregatorProjectName();
    _builder.append(_aggregatorProjectName, "\t");
    _builder.append("</artifactId>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<version>");
    String _pomProjectVersion = this.projectInfo.getPomProjectVersion();
    _builder.append(_pomProjectVersion, "\t");
    _builder.append("</version>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<packaging>pom</packaging>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<properties>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<license.copyrightOwners>Lunifera GmbH</license.copyrightOwners>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<lunifera.gitrepo.name>sample-");
    String _applicationName = this.projectInfo.getApplicationName();
    _builder.append(_applicationName, "\t\t");
    _builder.append("</lunifera.gitrepo.name>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("<lunifera.releng.version>0.12.3-SNAPSHOT</lunifera.releng.version>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</properties>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<modules>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<module>bundles/");
    String _bootstrapProjectName = this.projectInfo.getBootstrapProjectName();
    _builder.append(_bootstrapProjectName, "\t\t");
    _builder.append("</module>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("<module>bundles/");
    String _dtoServicesProjectName = this.projectInfo.getDtoServicesProjectName();
    _builder.append(_dtoServicesProjectName, "\t\t");
    _builder.append("</module>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("<module>bundles/");
    String _entityProjectName = this.projectInfo.getEntityProjectName();
    _builder.append(_entityProjectName, "\t\t");
    _builder.append("</module>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("<module>bundles/");
    String _testProjectName = this.projectInfo.getTestProjectName();
    _builder.append(_testProjectName, "\t\t");
    _builder.append("</module>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("<module>bundles/");
    String _uiApplicationProjectName = this.projectInfo.getUiApplicationProjectName();
    _builder.append(_uiApplicationProjectName, "\t\t");
    _builder.append("</module>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("<module>bundles/");
    String _uiMobileProjectName = this.projectInfo.getUiMobileProjectName();
    _builder.append(_uiMobileProjectName, "\t\t");
    _builder.append("</module>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<module>features/");
    String _featureProjectName = this.projectInfo.getFeatureProjectName();
    _builder.append(_featureProjectName, "\t\t");
    _builder.append("</module>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<module>releng/");
    String _p2ProjectName = this.projectInfo.getP2ProjectName();
    _builder.append(_p2ProjectName, "\t\t");
    _builder.append("</module>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("<module>releng/");
    String _productConfigProjectName = this.projectInfo.getProductConfigProjectName();
    _builder.append(_productConfigProjectName, "\t\t");
    _builder.append("</module>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("</modules>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<repositories>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<repository>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<id>oss.sonatype.org-snapshot</id>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<url>http://oss.sonatype.org/content/repositories/snapshots</url>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<releases>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<enabled>false</enabled>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</releases>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<snapshots>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<updatePolicy>always</updatePolicy>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<enabled>true</enabled>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</snapshots>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</repository>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<repository>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<id>lunifera-nexus-snapshots</id>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<name>Lunifera Nexus Snapshots</name>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<url>http://maven.lunifera.org:8086/nexus/content/repositories/snapshots/</url>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<releases>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<enabled>false</enabled>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</releases>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<snapshots>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<updatePolicy>always</updatePolicy>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<enabled>true</enabled>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</snapshots>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</repository>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<repository>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<id>lunifera-nexus-release</id>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<name>Lunifera Nexus Release</name>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<url>http://maven.lunifera.org:8086/nexus/content/repositories/releases/</url>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<releases>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<enabled>true</enabled>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</releases>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<snapshots>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<enabled>false</enabled>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</snapshots>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</repository>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<repository>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<id>lunifera-snapshots</id>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<url>http://lun.lunifera.org/downloads/p2/lunifera/luna/latest/</url>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<layout>p2</layout>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</repository>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<repository>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<id>xtext</id>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<url>http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/</url>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<layout>p2</layout>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</repository>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</repositories>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<build>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<pluginManagement>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<plugins>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<plugin>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<groupId>org.eclipse.tycho</groupId>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<artifactId>target-platform-configuration</artifactId>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<version>${tycho-version}</version>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<configuration>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<resolver>p2</resolver>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<pomDependencies>consider</pomDependencies>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<environments>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<environment>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<os>win32</os>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<ws>win32</ws>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<arch>x86_64</arch>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</environment>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<environment>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<os>linux</os>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<ws>gtk</ws>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<arch>x86</arch>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</environment>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<environment>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<os>linux</os>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<ws>gtk</ws>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<arch>x86_64</arch>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</environment>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<environment>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<os>macosx</os>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<ws>cocoa</ws>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<arch>x86_64</arch>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</environment>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</environments>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</configuration>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</plugin>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</plugins>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</pluginManagement>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<plugins>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<plugin>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<artifactId>maven-clean-plugin</artifactId>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<configuration>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<filesets>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<fileset>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<directory>xtend-gen</directory>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<includes>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("<include>**</include>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("</includes>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</fileset>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</filesets>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</configuration>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</plugin>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<plugin>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<groupId>org.eclipse.xtend</groupId>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<artifactId>xtend-maven-plugin</artifactId>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<executions>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<execution>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<goals>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<goal>compile</goal>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<goal>testCompile</goal>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</goals>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<configuration>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<outputDirectory>xtend-gen</outputDirectory>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("</configuration>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</execution>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</executions>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</plugin>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</plugins>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</build>");
    _builder.newLine();
    _builder.append("</project>");
    _builder.newLine();
    return this.writeToFile(_builder, fileWriter, "pom.xml");
  }
}
